### ISSUE TITLE
Unable to use Admin Dashboard.

### ISSUE THREAD

**Issue by dep1engenharia** [Babadinho/buy-sell#4]
Hello Dear Babadinho.

I have an admin user and I'm trying to access http://localhost:3000/admin/dashboard so that I can approve one listing.

But I can't do it because that error occours, do you have any clue on this?

Thank you.

Uncaught runtime errors:
×
ERROR
Cannot read properties of null (reading '_id')
TypeError: Cannot read properties of null (reading '_id')
    at http://localhost:3000/static/js/bundle.js:2765:61
    at Array.map (<anonymous>)
    at AdminDashboard (http://localhost:3000/static/js/bundle.js:2656:35)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:101627:22)
    at updateFunctionComponent (http://localhost:3000/static/js/bundle.js:103729:24)
    at beginWork (http://localhost:3000/static/js/bundle.js:105176:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:92202:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:92246:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:92301:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:109297:11)
ERROR
Cannot read properties of null (reading '_id')
TypeError: Cannot read properties of null (reading '_id')
    at http://localhost:3000/static/js/bundle.js:2765:61
    at Array.map (<anonymous>)
    at AdminDashboard (http://localhost:3000/static/js/bundle.js:2656:35)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:101627:22)
    at updateFunctionComponent (http://localhost:3000/static/js/bundle.js:103729:24)
    at beginWork (http://localhost:3000/static/js/bundle.js:105176:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:92202:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:92246:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:92301:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:109297:11)

**Comment by dep1engenharia** [comment]
I managed to make it work.

One of my database objects was with an incorrect data structure.
After I delete the record the Admin Panel started working again.

Thank you anyway.
